-- SOURCE (OLTP) system in schema `public`. Not exposed to the app role: the app only reads `dw`.
-- Amounts are integer cents in the row's own currency.

CREATE TABLE customers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         TEXT        NOT NULL,
    email             TEXT        NOT NULL,          -- PII
    phone             TEXT,                          -- PII, often NULL
    country           TEXT,                          -- ISO 3166-1 alpha-2, NULL for some
    marketing_opt_in  BOOLEAN     NOT NULL DEFAULT FALSE,
    is_test_account   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT    NOT NULL,
    category     TEXT    NOT NULL,
    subcategory  TEXT    NOT NULL,
    brand        TEXT    NOT NULL,
    price_cents  INTEGER NOT NULL CHECK (price_cents >= 0),  -- current list price, USD
    is_active    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT      NOT NULL REFERENCES customers(id),
    status        TEXT        NOT NULL
                  CHECK (status IN ('pending','paid','shipped','delivered','cancelled')),
    currency      TEXT        NOT NULL CHECK (currency IN ('USD','EUR','GBP')),
    total_cents   INTEGER,                           -- NULL on some legacy orders
    created_at    TIMESTAMPTZ NOT NULL,
    channel       TEXT        NOT NULL CHECK (channel IN ('web','mobile_app','marketplace','phone'))
);

CREATE TABLE order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT  NOT NULL REFERENCES orders(id),
    product_id        BIGINT  NOT NULL REFERENCES products(id),
    quantity          INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_cents  INTEGER NOT NULL CHECK (unit_price_cents >= 0),  -- price at time of sale
    discount_cents    INTEGER NOT NULL DEFAULT 0 CHECK (discount_cents >= 0)  -- line-level discount
);

CREATE TABLE payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT      NOT NULL REFERENCES orders(id),
    amount_cents  INTEGER     NOT NULL CHECK (amount_cents >= 0),
    method        TEXT        NOT NULL CHECK (method IN ('card','paypal','bank_transfer')),
    status        TEXT        NOT NULL CHECK (status IN ('succeeded','failed','pending')),
    card_last4    TEXT,                              -- PII-ish, card payments only
    paid_at       TIMESTAMPTZ                        -- NULL unless status = 'succeeded'
);

CREATE TABLE refunds (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id    BIGINT      NOT NULL REFERENCES payments(id),
    amount_cents  INTEGER     NOT NULL CHECK (amount_cents > 0),
    reason        TEXT,
    created_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE subscriptions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          BIGINT      NOT NULL REFERENCES customers(id),
    plan                 TEXT        NOT NULL CHECK (plan IN ('basic','pro','enterprise')),
    status               TEXT        NOT NULL CHECK (status IN ('active','past_due','cancelled')),
    monthly_price_cents  INTEGER     NOT NULL,       -- USD
    started_at           TIMESTAMPTZ NOT NULL,
    cancelled_at         TIMESTAMPTZ                 -- set only when status = 'cancelled'
);

CREATE INDEX idx_orders_customer    ON orders(customer_id);
CREATE INDEX idx_orders_created_at  ON orders(created_at);
CREATE INDEX idx_items_order        ON order_items(order_id);
CREATE INDEX idx_items_product      ON order_items(product_id);
CREATE INDEX idx_payments_order     ON payments(order_id);
CREATE INDEX idx_refunds_payment    ON refunds(payment_id);
CREATE INDEX idx_subs_customer      ON subscriptions(customer_id);
